"""
Contracts for adaptive follow-up and guiding questions.
Контракты для адаптивных уточняющих и наводящих вопросов.
"""
from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field

from contracts.domain import EvidenceRef


class FollowUpKind(str, Enum):
    """Type of suggestion."""
    CLARIFY = "clarify"
    DEEPEN = "deepen"
    GUIDE = "guide"


class FollowUpMode(str, Enum):
    """Generation mode: probe (clarify/deepen) or guide (guiding question)."""
    PROBE = "probe"
    GUIDE = "guide"


class FollowUpTrigger(str, Enum):
    """How the request was triggered."""
    AUTO = "auto"
    MANUAL = "manual"


class FollowUpStatus(str, Enum):
    """Interviewer decision status for a suggestion."""
    SUGGESTED = "suggested"
    ASKED = "asked"
    DISMISSED = "dismissed"


class FollowUpLLMSuggestion(BaseModel):
    """Single question suggestion generated by LLM."""
    kind: Literal["clarify", "deepen", "guide"]
    question_text: str = Field(..., min_length=1, max_length=400)
    purpose: str = Field(..., min_length=1, max_length=240)
    criterion_ids: list[str] = Field(..., min_length=1)
    source_refs: list[EvidenceRef] = Field(default_factory=list, max_length=3)

    model_config = {"extra": "forbid"}


class FollowUpLLMResponse(BaseModel):
    """Root structured response from LLM."""
    suggestions: list[FollowUpLLMSuggestion] = Field(default_factory=list)

    model_config = {"extra": "forbid"}


class FollowUpSuggestion(BaseModel):
    """
    Stored and domain-level representation of a follow-up card.
    Карточка предложения уточняющего или наводящего вопроса.
    """
    id: str
    request_id: str
    interview_id: str
    question_id: str
    rubric_revision_id: str
    transcript_revision_id: str
    kind: FollowUpKind
    question_text: str = Field(..., min_length=1, max_length=400)
    purpose: str = Field(..., min_length=1, max_length=240)
    criterion_ids: list[str] = Field(..., min_length=1)
    source_refs: list[EvidenceRef] = Field(default_factory=list, max_length=3)
    status: FollowUpStatus = FollowUpStatus.SUGGESTED
    asked_text: str | None = None
    ordinal: int = 0
    decided_at: datetime | None = None
    decision_version: int = 1
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    # Presentation / computed fields
    is_stale: bool = False
    stale_reason: str | None = None
    has_new_answer: bool = False


class GenerateFollowUpsRequest(BaseModel):
    """Request payload for triggering follow-up generation."""
    question_id: str = Field(..., min_length=1)
    mode: FollowUpMode = FollowUpMode.PROBE
    trigger: FollowUpTrigger = FollowUpTrigger.MANUAL
    expected_rubric_revision_id: str | None = None
    expected_transcript_revision_id: str | None = None
    expected_context_hash: str | None = None


class PatchFollowUpSuggestionRequest(BaseModel):
    """Request payload for updating human decision on a suggestion card."""
    status: FollowUpStatus
    asked_text: str | None = None
    expected_decision_version: int = Field(..., ge=1)
    expected_rubric_revision_id: str | None = None
    expected_transcript_revision_id: str | None = None


class FollowUpsStateResponse(BaseModel):
    """Response payload for GET /followups query."""
    interview_id: str
    question_id: str
    mode: FollowUpMode
    active_rubric_revision_id: str
    active_transcript_revision_id: str
    candidate_fingerprint: str | None = None
    context_hash: str | None = None
    can_generate: bool = False
    wait_reason: str | None = None
    cooldown_remaining_sec: float | None = None
    cooldown_seconds_remaining: int = 0
    active_request_id: str | None = None
    status: str = "idle"
    error_message: str | None = None
    latest_request: dict | None = None
    suggestions: list[FollowUpSuggestion] = Field(default_factory=list)
    has_new_answer: bool = False
    history: list[FollowUpSuggestion] = Field(default_factory=list)
